"""add outbox status event_id composite index

Revision ID: 2c98eec9aa32
Revises: 20260427_140000
Create Date: 2026-05-11 20:05:08.593339
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2c98eec9aa32'
down_revision = '20260427_140000'
branch_labels = None
depends_on = None


def _is_sqlite() -> bool:
    return op.get_bind().dialect.name == "sqlite"


def upgrade() -> None:
    if _is_sqlite():
        op.create_index('ix_outbox_status_event_id', 'outbox', ['status', 'event_id'], unique=False)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist_sync_runs', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('artists', 'sync_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('job_events', 'stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='ck_job_events_stage', native_enum=False, create_constraint=True),
               existing_nullable=True)
    op.alter_column('jobs', 'current_stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='stagetype', native_enum=False, create_constraint=True),
               existing_nullable=True)
    op.create_index('ix_outbox_status_event_id', 'outbox', ['status', 'event_id'], unique=False)
    op.alter_column('pipeline_stage_executions', 'stage',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='stagetype', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('pipeline_stage_executions', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('review_items', 'review_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TRANSCRIPT_REVIEW', 'TASTE_AUDIT', 'MANUAL_REVIEW', 'TRANSLATION_REVIEW', 'FINAL_ASSET_APPROVAL', name='reviewtype', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('review_items', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('subtitles', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               existing_nullable=False)
    op.alter_column('video_candidates', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DISCOVERED', 'DOWNLOADING', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', name='candidatestatus', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('video_candidates', 'ingestion_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('videos', 'processed_status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    if _is_sqlite():
        op.drop_index('ix_outbox_status_event_id', table_name='outbox')
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'processed_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('video_candidates', 'ingestion_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('video_candidates', 'status',
               existing_type=sa.Enum('DISCOVERED', 'DOWNLOADING', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', name='candidatestatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending_review'::character varying"))
    op.alter_column('subtitles', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('review_items', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('review_items', 'review_type',
               existing_type=sa.Enum('TRANSCRIPT_REVIEW', 'TASTE_AUDIT', 'MANUAL_REVIEW', 'TRANSLATION_REVIEW', 'FINAL_ASSET_APPROVAL', name='reviewtype', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('pipeline_stage_executions', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRY_SCHEDULED', 'DLQ', name='stagestatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('pipeline_stage_executions', 'stage',
               existing_type=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='stagetype', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_index('ix_outbox_status_event_id', table_name='outbox')
    op.alter_column('jobs', 'current_stage',
               existing_type=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='stagetype', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('job_events', 'stage',
               existing_type=sa.Enum('DOWNLOAD', 'TRANSCRIBE', 'AUDIT', 'MANUAL_REVIEW', 'TRANSLATE', 'TRANSLATION_REVIEW', 'RENDER', name='ck_job_events_stage', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('artists', 'sync_status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('artist_sync_runs', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='syncstatus', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
